import React from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Deck } from '../domain/models';
import { theme as T } from './theme';

export function Button({label,onPress,secondary=false}:{label:string;onPress?:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,pressed&&s.pressed]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{label}</Text>{!secondary&&<Text style={s.arrow}>→</Text>}</Pressable>}
export function Header({title,subtitle}:{title:string;subtitle?:string}){return <View style={s.header}><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>}
export function DeckRow({deck,onPress}:{deck:Deck;onPress:()=>void}){const pct=Math.min(100,deck.cards.length?Math.round(deck.cards.filter(c=>!c.suspended).length/deck.cards.length*100):0);return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.deck,pressed&&s.pressed]}><View style={[s.mark,{backgroundColor:deck.accent}]}/><View style={s.deckBody}><View style={s.row}><Text style={s.deckName} numberOfLines={1}>{deck.name}</Text><Text style={s.due}>{deck.cards.filter(c=>!c.suspended).length} cards</Text></View><Text style={s.deckSub}>{deck.subject}</Text><View style={s.track}><View style={[s.fill,{width:`${pct}%`,backgroundColor:deck.accent}]}/></View><Text style={s.meta}>{pct}% available · {deck.cards.length} total</Text></View><Text style={s.chevron}>›</Text></Pressable>}
export function Field({label,value,onChangeText,placeholder,multiline=false}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;multiline?:boolean}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={T.colors.faint} multiline={multiline} style={[s.field,multiline&&s.area]}/></View>}
export const styles=s;
const s=StyleSheet.create({header:{marginBottom:22},title:{fontSize:29,fontWeight:'800',letterSpacing:-1,color:T.colors.ink},subtitle:{fontSize:12,color:T.colors.muted,marginTop:4},button:{height:52,borderRadius:16,backgroundColor:T.colors.accent,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},secondary:{backgroundColor:T.colors.surface,borderWidth:1,borderColor:T.colors.line},buttonText:{fontSize:14,fontWeight:'800',color:'#FFF'},secondaryText:{color:T.colors.ink},arrow:{fontSize:22,color:'#FFF'},pressed:{opacity:.78,transform:[{scale:.992}]},deck:{backgroundColor:T.colors.surface,borderRadius:19,borderWidth:1,borderColor:T.colors.line,padding:15,flexDirection:'row',alignItems:'center',marginBottom:10},mark:{width:5,alignSelf:'stretch',borderRadius:4,marginRight:13},deckBody:{flex:1},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},deckName:{fontSize:16,fontWeight:'800',color:T.colors.ink,flexShrink:1},due:{fontSize:10,fontWeight:'800',color:T.colors.accent,marginLeft:8},deckSub:{fontSize:12,color:T.colors.muted,marginTop:3},track:{height:5,backgroundColor:'#EFECF0',borderRadius:4,overflow:'hidden',marginTop:11},fill:{height:5,borderRadius:4},meta:{fontSize:10,color:T.colors.faint,marginTop:5},chevron:{fontSize:25,color:T.colors.faint,marginLeft:9},label:{fontSize:9,fontWeight:'800',letterSpacing:1.2,color:T.colors.muted,marginTop:16,marginBottom:7},field:{minHeight:50,borderWidth:1,borderColor:T.colors.line,borderRadius:14,backgroundColor:T.colors.surface,paddingHorizontal:14,color:T.colors.ink,fontSize:14},area:{minHeight:105,paddingTop:13,textAlignVertical:'top'}});
