import React from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Deck } from '../domain/models';
import { theme as T } from './theme';

const s=StyleSheet.create({header:{marginBottom:24},title:{fontSize:28,fontWeight:'800',letterSpacing:-.8,color:T.colors.ink},subtitle:{fontSize:13,color:T.colors.muted,marginTop:5},button:{minHeight:48,borderRadius:12,backgroundColor:T.colors.accent,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},secondary:{backgroundColor:T.colors.surface,borderWidth:1,borderColor:T.colors.line},buttonText:{fontSize:14,fontWeight:'800',color:'#FFF'},secondaryText:{color:T.colors.ink},arrow:{fontSize:20,color:'#FFF'},pressed:{opacity:.72},deck:{backgroundColor:T.colors.surface,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:15,flexDirection:'row',alignItems:'center'},mark:{width:4,height:48,borderRadius:2,marginRight:13},deckBody:{flex:1},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},deckName:{fontSize:16,fontWeight:'800',color:T.colors.ink,flexShrink:1},due:{fontSize:11,fontWeight:'800',color:T.colors.accent,marginLeft:8},deckSub:{fontSize:12,color:T.colors.muted,marginTop:3},track:{height:4,backgroundColor:'#E9E4DD',borderRadius:2,overflow:'hidden',marginTop:10},fill:{height:4,borderRadius:2},meta:{fontSize:10,color:T.colors.faint,marginTop:5},chevron:{fontSize:24,color:T.colors.faint,marginLeft:10},label:{fontSize:10,fontWeight:'800',letterSpacing:1.1,color:T.colors.muted,marginTop:16,marginBottom:7},field:{minHeight:50,borderWidth:1,borderColor:T.colors.line,borderRadius:10,backgroundColor:T.colors.surface,paddingHorizontal:13,color:T.colors.ink,fontSize:14},area:{minHeight:105,paddingTop:13,textAlignVertical:'top'}});
export function Button({label,onPress,secondary=false}:{label:string;onPress?:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.button,secondary&&s.secondary,pressed&&s.pressed]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{label}</Text>{!secondary&&<Text style={s.arrow}>→</Text>}</Pressable>}
export function Header({title,subtitle}:{title:string;subtitle?:string}){return <View style={s.header}><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>}
export function DeckRow({deck,onPress}:{deck:Deck;onPress:()=>void}){const active=deck.cards.filter(c=>!c.suspended).length;const pct=Math.min(100,deck.cards.length?Math.round(active/deck.cards.length*100):0);return <Pressable accessibilityRole="button" onPress={onPress} style={({pressed})=>[s.deck,pressed&&s.pressed]}><View style={[s.mark,{backgroundColor:deck.accent}]}/><View style={s.deckBody}><View style={s.row}><Text style={s.deckName} numberOfLines={1}>{deck.name}</Text><Text style={s.due}>{active} cards</Text></View><Text style={s.deckSub}>{deck.subject}</Text><View style={s.track}><View style={[s.fill,{width:`${pct}%`,backgroundColor:deck.accent}]}/></View><Text style={s.meta}>{pct}% active · {deck.cards.length} total</Text></View><Text style={s.chevron}>›</Text></Pressable>}
export function Field({label,value,onChangeText,placeholder,multiline=false}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;multiline?:boolean}){return <View><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={T.colors.faint} multiline={multiline} style={[s.field,multiline&&s.area]}/></View>}
export const styles=s;
