import React,{useMemo} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {DashboardState,Deck} from '../domain/models';
import {Button,DeckRow} from './components';
import {theme as T} from './theme';
import {FadeIn,LiftIn} from './motion';

type Props={decks:Deck[];dashboard:DashboardState;schedulingEnabled:boolean;onStudy:(deckId:string)=>void;onLibrary:()=>void};
export function HomeScreen({decks,dashboard,schedulingEnabled,onStudy,onLibrary}:Props){
 const recommended=decks.find(d=>d.id===dashboard.queue.recommendedDeckId)||decks[0];
 const total=dashboard.queue.total;const focus=dashboard.queue.due.length?`${dashboard.queue.due.length} due now`:dashboard.queue.learning.length?`${dashboard.queue.learning.length} in learning`:dashboard.queue.newCards.length?`${dashboard.queue.newCards.length} new cards`:'Nothing is waiting';
 const status=dashboard.queue.due.length?'REVIEW':dashboard.queue.learning.length?'REINFORCE':dashboard.queue.newCards.length?'LEARN':'CLEAR';
 const recent=useMemo(()=>decks.filter(d=>dashboard.deckSummaries.some(s=>s.deckId===d.id)).slice(0,4),[decks,dashboard.deckSummaries]);
 return <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
  <FadeIn><View style={s.top}><Text style={s.wordmark}>QUICKREVIEW</Text><Text style={s.date}>{new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}).toUpperCase()}</Text></View></FadeIn>
  <LiftIn><View style={s.command}><View style={s.commandHead}><Text style={s.kicker}>TODAY</Text><Text style={s.state}>{status}</Text></View><Text style={s.number}>{total}</Text><Text style={s.headline}>{total?'items ready for deliberate practice.':'Your queue is clear.'}</Text><Text style={s.detail}>{focus}{schedulingEnabled?' · scheduled from your review history.':' · scheduling is off, so active material is available on demand.'}</Text>{recommended&&total>0?<Button label={dashboard.queue.due.length?'Start review':'Continue studying'} onPress={()=>onStudy(recommended.id)}/>:<Button label="Open your library" secondary onPress={onLibrary}/>}<View style={s.rule}/><View style={s.micro}><Text style={s.microStrong}>{dashboard.reviewsToday}</Text><Text style={s.microLabel}>REVIEWED TODAY</Text><View style={s.microSep}/><Text style={s.microStrong}>{dashboard.totalActive}</Text><Text style={s.microLabel}>ACTIVE CARDS</Text></View></View></LiftIn>
  <View style={s.path}><Text style={s.sectionKicker}>THE LOOP</Text><View style={s.pathRow}><Step n="01" title="Learn" body="Understand the concept" active={!dashboard.queue.due.length}/><Text style={s.pathArrow}>→</Text><Step n="02" title="Practice" body="Retrieve from memory" active={Boolean(dashboard.queue.due.length)}/><Text style={s.pathArrow}>→</Text><Step n="03" title="Return" body="Come back when needed" active={schedulingEnabled}/></View></View>
  <View style={s.decksHead}><View><Text style={s.sectionTitle}>Your material</Text><Text style={s.sectionSub}>The system chooses a starting point; you choose the topic.</Text></View><Pressable onPress={onLibrary} hitSlop={10}><Text style={s.link}>Library ↗</Text></Pressable></View>
  {recent.length?recent.map(d=><FadeIn key={d.id}><DeckRow deck={d} onPress={()=>onStudy(d.id)}/></FadeIn>):<View style={s.empty}><Text style={s.emptyTitle}>Your learning system starts here.</Text><Text style={s.emptyText}>Import or create material in the Library.</Text><Button label="Open library" onPress={onLibrary}/></View>}
 </ScrollView>
}
function Step({n,title,body,active}:{n:string;title:string;body:string;active:boolean}){return <View style={[s.step,active&&s.stepActive]}><Text style={[s.stepN,active&&s.stepNActive]}>{n}</Text><Text style={s.stepTitle}>{title}</Text><Text style={s.stepBody}>{body}</Text></View>}
const s=StyleSheet.create({scroll:{paddingHorizontal:20,paddingTop:18,paddingBottom:54},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:30},wordmark:{fontSize:10,fontWeight:'900',letterSpacing:2.6,color:T.colors.accentInk},date:{fontSize:8,fontWeight:'900',letterSpacing:1,color:T.colors.faint},command:{backgroundColor:T.colors.dark,padding:22,borderRadius:T.radius.xl,marginBottom:32},commandHead:{flexDirection:'row',justifyContent:'space-between'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.6,color:T.colors.darkMuted},state:{fontSize:9,fontWeight:'900',letterSpacing:1.4,color:T.colors.accent},number:{fontSize:74,lineHeight:78,fontWeight:'900',letterSpacing:-5,color:T.colors.white,marginTop:8},headline:{fontSize:20,lineHeight:25,fontWeight:'900',color:T.colors.white,maxWidth:290},detail:{fontSize:11,lineHeight:17,color:T.colors.darkMuted,marginTop:7,marginBottom:18},rule:{height:1,backgroundColor:'#303530',marginTop:18},micro:{flexDirection:'row',alignItems:'center',marginTop:13},microStrong:{fontSize:15,fontWeight:'900',color:T.colors.white},microLabel:{fontSize:7,fontWeight:'900',letterSpacing:1,color:'#7F8982',marginLeft:5},microSep:{width:1,height:18,backgroundColor:'#303530',marginHorizontal:13},path:{borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:17,marginBottom:30},sectionKicker:{fontSize:8,fontWeight:'900',letterSpacing:1.5,color:T.colors.faint,marginBottom:14},pathRow:{flexDirection:'row',alignItems:'stretch'},step:{flex:1,opacity:.55},stepActive:{opacity:1},stepN:{fontSize:8,fontWeight:'900',color:T.colors.faint,marginBottom:8},stepNActive:{color:T.colors.accentInk},stepTitle:{fontSize:13,fontWeight:'900',color:T.colors.ink},stepBody:{fontSize:9,lineHeight:13,color:T.colors.muted,marginTop:3},pathArrow:{fontSize:16,color:T.colors.faint,marginHorizontal:6,alignSelf:'center'},decksHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginBottom:11},sectionTitle:{fontSize:19,fontWeight:'900',letterSpacing:-.4,color:T.colors.ink},sectionSub:{fontSize:10,lineHeight:15,color:T.colors.muted,marginTop:3,maxWidth:280},link:{fontSize:10,fontWeight:'900',color:T.colors.accentInk,paddingVertical:6},empty:{borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:22},emptyTitle:{fontSize:18,fontWeight:'900',color:T.colors.ink},emptyText:{fontSize:11,color:T.colors.muted,marginTop:4,marginBottom:16}});
