import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Deck, ReviewRecord } from '../domain/models';
import { DeckRow, Button } from './components';
import { theme as T } from './theme';
import { FadeIn, LiftIn } from './motion';

type Props={decks:Deck[];reviews:ReviewRecord[];schedulingEnabled:boolean;onStudy:(deckId:string)=>void;onDecks:()=>void;onLibrary:()=>void};

function counts(deck:Deck){const now=Date.now();const active=deck.cards.filter(c=>!c.suspended);const due=active.filter(c=>!c.dueAt||new Date(c.dueAt).getTime()<=now);const newCards=active.filter(c=>!c.intervalDays&&!c.dueAt);const learning=active.filter(c=>c.dueAt&&(!c.intervalDays||c.intervalDays===0));const review=due.filter(c=>Boolean(c.intervalDays));return {active:active.length,due:due.length,newCards:newCards.length,learning:learning.length,review:review.length}}

export function HomeScreen({decks,reviews,schedulingEnabled,onStudy,onDecks,onLibrary}:Props){
 const totals=useMemo(()=>decks.reduce((a,d)=>{const c=counts(d);a.active+=c.active;a.due+=c.due;a.newCards+=c.newCards;a.learning+=c.learning;a.review+=c.review;return a},{active:0,due:0,newCards:0,learning:0,review:0}),[decks]);
 const today=new Date().toISOString().slice(0,10);const todayReviews=reviews.filter(r=>r.createdAt.slice(0,10)===today);const firstDeck=decks.find(d=>counts(d).due>0)||decks.find(d=>counts(d).active>0);
 return <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}>
  <FadeIn><View style={s.mast}><View><Text style={s.brand}>QUICKREVIEW</Text><Text style={s.title}>Study what matters.</Text><Text style={s.sub}>A focused place for recall, review, and progress.</Text></View><View style={s.day}><Text style={s.dayNumber}>{today.slice(-2)}</Text><Text style={s.dayLabel}>DAY</Text></View></View></FadeIn>
  <LiftIn><View style={s.focus}><View style={s.focusTop}><View><Text style={s.eyebrow}>{schedulingEnabled?'TODAY'S REVIEW':'STUDY QUEUE'}</Text><Text style={s.focusTitle}>{schedulingEnabled?'Your due cards are waiting.':'Build a session from your active cards.'}</Text></View><Text style={s.focusCount}>{totals.due}</Text></View><View style={s.breakdown}><View><Text style={s.breakValue}>{totals.newCards}</Text><Text style={s.breakLabel}>NEW</Text></View><View><Text style={s.breakValue}>{totals.learning}</Text><Text style={s.breakLabel}>LEARNING</Text></View><View><Text style={s.breakValue}>{totals.review}</Text><Text style={s.breakLabel}>REVIEW</Text></View></View><Button label={firstDeck&&totals.due?'Start review':'Choose a deck'} onPress={()=>firstDeck&&onStudy(firstDeck.id)} disabled={!firstDeck||!totals.due}/><Text style={s.focusNote}>{todayReviews.length} reviews today · {totals.active} active cards</Text></View></LiftIn>
  <View style={s.section}><View><Text style={s.sectionTitle}>Your decks</Text><Text style={s.sectionSub}>Pick a topic, then stay in the flow.</Text></View><Pressable onPress={onDecks} hitSlop={10} accessibilityRole="button"><Text style={s.link}>Manage ↗</Text></Pressable></View>
  {decks.length?decks.slice(0,5).map(d=><FadeIn key={d.id}><DeckRow deck={d} onPress={()=>onStudy(d.id)}/></FadeIn>):<View style={s.empty}><Text style={s.emptyEyebrow}>START HERE</Text><Text style={s.emptyTitle}>Create one small deck.</Text><Text style={s.emptyText}>One exam, one chapter, one useful topic.</Text><Button label="Create a deck" onPress={onDecks}/></View>}
  <View style={s.tools}><View style={s.section}><View><Text style={s.sectionTitle}>Build</Text><Text style={s.sectionSub}>Bring knowledge into the system.</Text></View></View><Pressable accessibilityRole="button" onPress={onDecks} style={s.tool}><Text style={s.toolIndex}>01</Text><View style={s.toolCopy}><Text style={s.toolTitle}>New deck</Text><Text style={s.toolHint}>Start with a focused topic</Text></View><Text style={s.toolArrow}>↗</Text></Pressable><Pressable accessibilityRole="button" onPress={onLibrary} style={s.tool}><Text style={s.toolIndex}>02</Text><View style={s.toolCopy}><Text style={s.toolTitle}>Import material</Text><Text style={s.toolHint}>TXT, CSV, DOCX, PPTX, EPUB</Text></View><Text style={s.toolArrow}>↗</Text></Pressable></View>
 </ScrollView>;
}

const s=StyleSheet.create({
 scroll:{paddingHorizontal:20,paddingTop:18,paddingBottom:54},mast:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:32},brand:{fontSize:9,fontWeight:'900',letterSpacing:2.6,color:T.colors.accentInk},title:{fontSize:32,lineHeight:36,fontWeight:'900',letterSpacing:-1.7,color:T.colors.ink,marginTop:6},sub:{fontSize:12,lineHeight:18,color:T.colors.muted,marginTop:7,maxWidth:330},day:{width:44,height:44,borderWidth:1,borderColor:T.colors.line,justifyContent:'center',alignItems:'center',backgroundColor:T.colors.surface},dayNumber:{fontSize:16,fontWeight:'900',color:T.colors.ink},dayLabel:{fontSize:7,fontWeight:'900',letterSpacing:1,color:T.colors.faint,marginTop:1},
 focus:{backgroundColor:T.colors.dark,padding:20,borderRadius:T.radius.xl,marginBottom:36},focusTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.6,color:T.colors.darkMuted},focusTitle:{fontSize:18,lineHeight:23,fontWeight:'800',color:T.colors.white,marginTop:8,maxWidth:230},focusCount:{fontSize:68,lineHeight:68,fontWeight:'900',letterSpacing:-4,color:T.colors.accent,marginLeft:12},breakdown:{flexDirection:'row',gap:26,marginTop:22,marginBottom:19,paddingTop:15,borderTopWidth:1,borderTopColor:'#303530'},breakValue:{fontSize:18,fontWeight:'900',color:T.colors.white},breakLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:'#7F8982',marginTop:3},focusNote:{fontSize:9,color:'#7F8982',textAlign:'center',marginTop:10},
 section:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end',marginBottom:11},sectionTitle:{fontSize:19,fontWeight:'900',letterSpacing:-.4,color:T.colors.ink},sectionSub:{fontSize:10,color:T.colors.muted,marginTop:3},link:{fontSize:11,fontWeight:'900',color:T.colors.accentInk,paddingVertical:6},empty:{borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:22,marginBottom:30},emptyEyebrow:{fontSize:8,fontWeight:'900',letterSpacing:1.6,color:T.colors.accentInk},emptyTitle:{fontSize:18,fontWeight:'900',color:T.colors.ink,marginTop:6},emptyText:{fontSize:11,color:T.colors.muted,marginTop:3,marginBottom:16},tools:{marginTop:30},tool:{minHeight:68,borderTopWidth:1,borderColor:T.colors.line,flexDirection:'row',alignItems:'center'},toolIndex:{width:38,fontSize:9,fontWeight:'900',letterSpacing:1,color:T.colors.faint},toolCopy:{flex:1},toolTitle:{fontSize:14,fontWeight:'900',color:T.colors.ink},toolHint:{fontSize:10,color:T.colors.muted,marginTop:3},toolArrow:{fontSize:18,color:T.colors.faint}
});
