import React,{useMemo,useState} from 'react';
import {Image,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {CardType,Deck} from '../domain/models';
import {Button} from './components';
import {theme as T} from './theme';
import {FadeIn} from './motion';
const labels:Record<CardType,string>={basic:'Concept',reversed:'Reversed',cloze:'Cloze',multipleChoice:'Multiple choice',trueFalse:'True / False',typedAnswer:'Typed answer',image:'Visual',imageOcclusion:'Visual'};
const clozeText=(text:string)=>text.replace(/\{\{\s*([^{}]+?)\s*\}\}/g,'$1');
type Props={deck:Deck;onPractice:()=>void};
export function LearningScreen({deck,onPractice}:Props){
 const cards=useMemo(()=>deck.cards.filter(c=>!c.suspended),[deck]);const [index,setIndex]=useState(0);const current=cards[index];
 if(!current)return <View style={s.empty}><Text style={s.eyebrow}>LEARN</Text><Text style={s.title}>Build the lesson first.</Text><Text style={s.body}>Add cards to {deck.name}, then come back here to study their meanings before practicing.</Text><Button label="Go to practice" secondary onPress={onPractice}/></View>;
 const term=current.type==='reversed'?current.back:current.front;const meaning=current.type==='reversed'?current.front:current.back;const next=()=>setIndex(v=>Math.min(cards.length-1,v+1));const previous=()=>setIndex(v=>Math.max(0,v-1));
 return <View style={s.root}><View style={s.header}><View style={s.headerCopy}><Text style={[s.deck,{color:deck.accent||T.colors.accentInk}]}>{deck.name.toUpperCase()}</Text><Text style={s.heading}>Learn</Text><Text style={s.sub}>Study the meaning before you test yourself.</Text></View><Pressable accessibilityRole="button" onPress={onPractice} style={s.practice}><Text style={s.practiceText}>Practice →</Text></Pressable></View><View style={s.lessonMeta}><Text style={s.metaStrong}>{String(index+1).padStart(2,'0')}</Text><Text style={s.metaText}>OF {String(cards.length).padStart(2,'0')}</Text><View style={s.metaLine}><View style={[s.metaFill,{width:`${((index+1)/cards.length)*100}%`,backgroundColor:deck.accent||T.colors.accent}]}/></View></View><FadeIn key={current.id}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><View style={[s.termBlock,{borderLeftColor:deck.accent||T.colors.accent}]}><Text style={s.section}>TERM / CONCEPT</Text><Text style={s.term}>{current.type==='cloze'?clozeText(term):term}</Text></View><View style={s.meaningBlock}><Text style={s.section}>MEANING</Text><Text style={s.meaning}>{meaning}</Text></View>{(current.type==='image'||current.type==='imageOcclusion')&&current.imageUri?<View style={s.visual}><Image source={{uri:current.imageUri}} resizeMode="contain" style={s.image}/></View>:null}{current.examples.length>0&&<View style={s.examples}><Text style={s.section}>EXAMPLES</Text>{current.examples.map((x,i)=><View key={`${x}-${i}`} style={s.example}><Text style={s.exampleNo}>{String(i+1).padStart(2,'0')}</Text><Text style={s.exampleText}>{x}</Text></View>)}</View>}<View style={s.check}><Text style={s.checkTitle}>Now try to explain it without looking.</Text><Text style={s.checkText}>This comes after the explanation, so learning never depends on hiding the material.</Text></View><Button label="Practice this deck" onPress={onPractice}/></ScrollView></FadeIn><View style={s.controls}><Pressable accessibilityRole="button" disabled={index===0} onPress={previous} style={[s.control,index===0&&s.disabled]}><Text style={s.controlText}>← Previous</Text></Pressable><Pressable accessibilityRole="button" disabled={index===cards.length-1} onPress={next} style={[s.control,index===cards.length-1&&s.disabled]}><Text style={s.controlText}>Next →</Text></Pressable></View></View>;
}
const s=StyleSheet.create({root:{flex:1,paddingHorizontal:20,paddingTop:18},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},headerCopy:{flex:1,paddingRight:12},deck:{fontSize:9,fontWeight:'900',letterSpacing:1.5},heading:{fontSize:34,fontWeight:'900',letterSpacing:-1.7,color:T.colors.ink,marginTop:2},sub:{fontSize:11,lineHeight:17,color:T.colors.muted,marginTop:3},practice:{paddingTop:8,minHeight:44,justifyContent:'center'},practiceText:{fontSize:11,fontWeight:'900',color:T.colors.accentInk},lessonMeta:{flexDirection:'row',alignItems:'center',marginTop:18,marginBottom:8},metaStrong:{fontSize:12,fontWeight:'900',color:T.colors.ink},metaText:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:T.colors.faint,marginLeft:6},metaLine:{flex:1,height:2,backgroundColor:T.colors.surface2,marginLeft:12},metaFill:{height:2},scroll:{paddingTop:10,paddingBottom:24},section:{fontSize:8,fontWeight:'900',letterSpacing:1.4,color:T.colors.faint,marginBottom:8},termBlock:{paddingLeft:16,borderLeftWidth:5,paddingVertical:4},term:{fontSize:27,lineHeight:34,fontWeight:'900',letterSpacing:-.8,color:T.colors.ink},meaningBlock:{marginTop:30,paddingTop:20,borderTopWidth:1,borderTopColor:T.colors.line},meaning:{fontSize:17,lineHeight:27,color:T.colors.ink},visual:{marginTop:22,borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:14},image:{width:'100%',height:190},examples:{marginTop:24},example:{flexDirection:'row',paddingVertical:8,borderBottomWidth:1,borderBottomColor:T.colors.line},exampleNo:{width:32,fontSize:9,fontWeight:'900',color:T.colors.accentInk},exampleText:{flex:1,fontSize:12,lineHeight:19,color:T.colors.muted},check:{marginTop:26,marginBottom:14,padding:16,backgroundColor:T.colors.surface2,borderLeftWidth:3,borderLeftColor:T.colors.accent},checkTitle:{fontSize:12,fontWeight:'900',color:T.colors.ink},checkText:{fontSize:10,lineHeight:16,color:T.colors.muted,marginTop:5},controls:{flexDirection:'row',borderTopWidth:1,borderTopColor:T.colors.line,paddingTop:8,paddingBottom:8,gap:8},control:{flex:1,minHeight:46,alignItems:'center',justifyContent:'center'},controlText:{fontSize:11,fontWeight:'900',color:T.colors.ink},disabled:{opacity:.3},empty:{flex:1,padding:24,justifyContent:'center'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.6,color:T.colors.accentInk},title:{fontSize:30,fontWeight:'900',color:T.colors.ink,marginTop:5},body:{fontSize:12,lineHeight:19,color:T.colors.muted,marginVertical:12}});
