import React,{useMemo,useState} from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Deck, makeId, now } from '../domain/models';
import { Button, DeckRow, Field, Header } from './components';
import { theme as T } from './theme';
import { FadeIn } from './motion';

type Tab='Home'|'Decks'|'Study'|'Library'|'Settings';
type Nav={go:(tab:Tab)=>void;select:(id:string)=>void};

export function Decks({decks,setDecks,nav}:{decks:Deck[];setDecks:React.Dispatch<React.SetStateAction<Deck[]>>;nav:Nav}){
 const [q,setQ]=useState('');const [filter,setFilter]=useState<'all'|'due'|'recent'>('all');const [open,setOpen]=useState(false);const [name,setName]=useState('');const [subject,setSubject]=useState('');
 const filtered=useMemo(()=>decks.filter(d=>(d.name+' '+d.subject).toLowerCase().includes(q.toLowerCase())).filter(d=>{if(filter==='all')return true;if(filter==='recent')return true;return d.cards.some(c=>!c.suspended&&(!c.dueAt||new Date(c.dueAt).getTime()<=Date.now()))}),[decks,q,filter]);
 const create=()=>{if(!name.trim())return;const t=now();setDecks(x=>[{id:makeId('deck'),name:name.trim(),subject:subject.trim()||'Personal study',accent:T.colors.accent,createdAt:t,updatedAt:t,cards:[]},...x]);setName('');setSubject('');setOpen(false)};
 return <View style={{flex:1}}><ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><Header title="Decks" subtitle="Keep each study topic small enough to finish."/><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={q} onChangeText={setQ} placeholder="Search decks" placeholderTextColor={T.colors.faint} style={s.searchInput} accessibilityLabel="Search decks"/></View><View style={s.filters}>{(['all','due','recent'] as const).map(value=><Pressable accessibilityRole="tab" accessibilityState={{selected:filter===value}} key={value} onPress={()=>setFilter(value)} style={[s.filter,filter===value&&s.filterActive]}><Text style={[s.filterText,filter===value&&s.filterTextActive]}>{value==='all'?'All':value==='due'?'Due':'Recent'}</Text></Pressable>)}</View>{filtered.map((d,i)=><FadeIn key={d.id} delay={Math.min(i*22,180)}><DeckRow deck={d} onPress={()=>{nav.select(d.id);nav.go('Study')}}/></FadeIn>)}{filtered.length===0&&<View style={s.empty}><Text style={s.emptyTitle}>No decks match.</Text><Text style={s.emptyText}>Try another search or create a focused deck.</Text></View>}<Pressable accessibilityRole="button" onPress={()=>setOpen(true)} style={({pressed})=>[s.create,pressed&&s.pressed]}><Text style={s.createText}>＋ Create a deck</Text></Pressable></ScrollView><Modal visible={open} transparent animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.backdrop}><View style={s.sheet}><View style={s.handle}/><View style={s.modalHead}><View><Text style={s.modalKicker}>NEW DECK</Text><Text style={s.modalTitle}>Give it a job.</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Close" onPress={()=>setOpen(false)} hitSlop={12}><Text style={s.close}>×</Text></Pressable></View><Field label="NAME" value={name} onChangeText={setName} placeholder="e.g. Environmental Science"/><Field label="SUBJECT · OPTIONAL" value={subject} onChangeText={setSubject} placeholder="e.g. Midterm · Lessons 1–6"/><Button label="Create deck" onPress={create}/></View></View></Modal></View>
}

const s=StyleSheet.create({scroll:{paddingHorizontal:20,paddingTop:18,paddingBottom:54},search:{height:52,borderWidth:1,borderColor:T.colors.line,backgroundColor:T.colors.surface,borderRadius:T.radius.sm,flexDirection:'row',alignItems:'center',paddingHorizontal:14},searchIcon:{fontSize:22,color:T.colors.muted,marginRight:8},searchInput:{flex:1,color:T.colors.ink,fontSize:14},filters:{flexDirection:'row',gap:20,marginTop:14,marginBottom:10},filter:{minHeight:40,justifyContent:'center'},filterActive:{borderBottomWidth:2,borderBottomColor:T.colors.accent},filterText:{fontSize:11,fontWeight:'800',color:T.colors.muted},filterTextActive:{color:T.colors.ink},create:{minHeight:52,borderWidth:1,borderColor:T.colors.ink,marginTop:18,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'center'},createText:{fontSize:12,fontWeight:'900',color:T.colors.ink},empty:{paddingVertical:26,borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line},emptyTitle:{fontSize:17,fontWeight:'900',color:T.colors.ink},emptyText:{fontSize:11,lineHeight:17,color:T.colors.muted,marginTop:4},pressed:{opacity:.7},backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.5)'},sheet:{backgroundColor:T.colors.bg,borderTopLeftRadius:T.radius.xl,borderTopRightRadius:T.radius.xl,padding:20,paddingBottom:30},handle:{width:34,height:4,borderRadius:2,backgroundColor:T.colors.line,alignSelf:'center',marginBottom:18},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},modalKicker:{fontSize:8,fontWeight:'900',letterSpacing:1.4,color:T.colors.accentInk},modalTitle:{fontSize:24,fontWeight:'900',color:T.colors.ink,marginTop:4},close:{fontSize:28,color:T.colors.muted}
});
