import React from 'react';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {AppSettings} from '../domain/models';
import {Header} from './components';
import {theme as T} from './theme';

type Props={settings:AppSettings;onChange:(next:AppSettings)=>Promise<void>};
const sizes=[5,10,20,30];
export function SettingsScreen({settings,onChange}:Props){const set=(patch:Partial<AppSettings>)=>onChange({...settings,...patch});return <ScrollView contentContainerStyle={s.scroll} showsVerticalScrollIndicator={false}><Header title="Settings" subtitle="Tune the system around how you actually study."/><Text style={s.label}>STUDY BEHAVIOR</Text><View style={s.section}><View style={s.row}><View style={s.copy}><Text style={s.title}>Spaced repetition</Text><Text style={s.hint}>Use due dates and review intervals instead of choosing cards manually.</Text></View><Pressable accessibilityRole="switch" accessibilityState={{checked:settings.schedulingEnabled}} onPress={()=>set({schedulingEnabled:!settings.schedulingEnabled})} style={[s.switch,settings.schedulingEnabled&&s.switchOn]}><View style={[s.knob,settings.schedulingEnabled&&s.knobOn]}/></Pressable></View><View style={s.rule}/><Text style={s.subLabel}>DEFAULT SESSION SIZE</Text><View style={s.sizeRow}>{sizes.map(n=><Pressable key={n} accessibilityRole="radio" accessibilityState={{selected:settings.defaultSessionSize===n}} onPress={()=>set({defaultSessionSize:n})} style={[s.size,settings.defaultSessionSize===n&&s.sizeActive]}><Text style={[s.sizeText,settings.defaultSessionSize===n&&s.sizeTextActive]}>{n}</Text></Pressable>)}</View><Text style={s.note}>{settings.schedulingEnabled?'New, learning, and due reviews are separated by the scheduler.':'Practice stays open and unscheduled.'}</Text></View><Text style={s.label}>INTERACTION</Text><View style={s.section}><View style={s.row}><View style={s.copy}><Text style={s.title}>Study gestures</Text><Text style={s.hint}>Keep gesture-based study interactions available where supported.</Text></View><Pressable accessibilityRole="switch" accessibilityState={{checked:settings.gesturesEnabled}} onPress={()=>set({gesturesEnabled:!settings.gesturesEnabled})} style={[s.switch,settings.gesturesEnabled&&s.switchOn]}><View style={[s.knob,settings.gesturesEnabled&&s.knobOn]}/></Pressable></View><View style={s.rule}/><View style={s.row}><View style={s.copy}><Text style={s.title}>Feedback</Text><Text style={s.hint}>Pressed states and focused haptics reinforce important actions.</Text></View><Text style={s.value}>ON</Text></View></View><Text style={s.label}>VISUAL SYSTEM</Text><View style={s.visual}><View style={s.swatchRow}><View style={[s.swatch,s.swatchBg]}/><View style={[s.swatch,s.swatchInk]}/><View style={[s.swatch,s.swatchAccent]}/></View><Text style={s.visualTitle}>High-contrast light</Text><Text style={s.visualText}>Quiet surfaces, strong type, and lime reserved for emphasis and action.</Text></View><Text style={s.label}>DATA</Text><View style={s.data}><Text style={s.title}>Local first</Text><Text style={s.hint}>Decks, reviews, and preferences are stored on this device by the current repository.</Text></View></ScrollView>}
const s=StyleSheet.create({scroll:{padding:20,paddingBottom:54},label:{fontSize:9,fontWeight:'900',letterSpacing:1.5,color:T.colors.faint,marginTop:8,marginBottom:8},section:{backgroundColor:T.colors.surface,borderTopWidth:1,borderBottomWidth:1,borderColor:T.colors.line,paddingVertical:4,marginBottom:22},row:{minHeight:56,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},copy:{flex:1,paddingRight:16},title:{fontSize:14,fontWeight:'900',color:T.colors.ink},hint:{fontSize:11,lineHeight:17,color:T.colors.muted,marginTop:4},rule:{height:1,backgroundColor:T.colors.line},subLabel:{fontSize:8,fontWeight:'900',letterSpacing:1.2,color:T.colors.faint,marginTop:14,marginBottom:8},switch:{width:48,height:28,borderRadius:14,backgroundColor:T.colors.surface2,padding:3,justifyContent:'center'},switchOn:{backgroundColor:T.colors.accent},knob:{width:22,height:22,borderRadius:11,backgroundColor:T.colors.white},knobOn:{alignSelf:'flex-end'},sizeRow:{flexDirection:'row',gap:8},size:{flex:1,minHeight:44,borderWidth:1,borderColor:T.colors.line,borderRadius:T.radius.sm,alignItems:'center',justifyContent:'center'},sizeActive:{backgroundColor:T.colors.ink,borderColor:T.colors.ink},sizeText:{fontSize:11,fontWeight:'900',color:T.colors.muted},sizeTextActive:{color:T.colors.white},note:{fontSize:10,lineHeight:16,color:T.colors.muted,marginTop:11},value:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:T.colors.accentInk},visual:{backgroundColor:T.colors.dark,borderRadius:T.radius.lg,padding:18,marginBottom:22},swatchRow:{flexDirection:'row',gap:8},swatch:{width:30,height:30,borderRadius:8},swatchBg:{backgroundColor:T.colors.surface},swatchInk:{backgroundColor:T.colors.ink},swatchAccent:{backgroundColor:T.colors.accent},visualTitle:{fontSize:16,fontWeight:'900',color:T.colors.white,marginTop:15},visualText:{fontSize:11,lineHeight:17,color:T.colors.darkMuted,marginTop:5},data:{paddingVertical:4,borderBottomWidth:1,borderColor:T.colors.line}}
);
